# The main entry point of Polylox workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


#report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
#singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk" 

rule all:
    input: expand(sample + ".hifi.bam", sample=samples), expand(sample + "._aggregated_data.csv", sample=samples)

include: "rules/lima.smk"
include: "rules/isoseq.smk"
include: "rules/map.smk"
include: "rules/scripts.smk"
